name: Build Packer AMI

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js dependencies
        run: npm install

      - name: Create .env file
        run: |
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env

      - name: Create ZIP artifact
        run: zip -r webapp.zip . -x ".github/*"  -x "*.git*" -x "README.md" -x "tests/*" -x "node_modules/*" -x "packer/*"

      - name: Verify ZIP contents
        run: unzip -l webapp.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: webapp
          path: webapp.zip

  build_ami:
    name: "Build AMI"
    runs-on: ubuntu-latest
    needs: build

    outputs:
      ami_id: ${{ steps.capture_ami.outputs.ami_id }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.PACKER_ACCESS_KEY}}
          aws-secret-access-key: ${{ secrets.PACKER_SECRET_KEY}}
          role-to-assume: ${{secrets.AWS_ROLE_ARN}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: webapp

      - name: Install Packer
        run: sudo apt-get install -y packer

      - name: Initialize Packer
        run: packer init ./packer/aws.pkr.hcl

      - name: Build Packer Image
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SOURCE_AMI: ${{ secrets.AWS_SOURCE_AMI }}
          INSTANCE_TYPE: ${{ secrets.INSTANCE_TYPE }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          AMI_NAME: ${{ secrets.AMI_NAME }}
          VOLUME_SIZE: ${{ secrets.VOLUME_SIZE }}
          VOLUME_TYPE: ${{ secrets.VOLUME_TYPE }}
          DEMO_ACCOUNT_ID: ${{secrets.DEMO_ACCOUNT_ID}}

        run: |
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')  # Generate timestamp in format YYYYMMDDHHMMSS
          packer build \
          -var "aws_region=${AWS_REGION}" \
          -var "aws_source_ami=${AWS_SOURCE_AMI}" \
          -var "instance_type=${INSTANCE_TYPE}" \
          -var "ssh_username=${SSH_USERNAME}" \
          -var "ami_name=${AMI_NAME}-${TIMESTAMP}" \
          -var "volume_size=${VOLUME_SIZE}" \
          -var "volume_type=${VOLUME_TYPE}" \
          -var "demo_account_id=${DEMO_ACCOUNT_ID}" \
          ./packer/aws.pkr.hcl | tee packer_output.txt

          # Extract AMI ID directly here
          AMI_ID=$(grep -Eo 'ami-[a-z0-9]+' packer_output.txt | tail -n1)
          echo "AMI_ID=$AMI_ID" >> $GITHUB_ENV

      - name: Capture AMI ID
        id: capture_ami
        run: |
          AMI_ID=$(grep -Eo 'ami-[a-z0-9]+' packer_output.txt | tail -n1)
          if [ -z "$AMI_ID" ]; then
            echo "Failed to extract AMI ID from Packer output."
            exit 1
          fi
          echo "ami_id=$AMI_ID" >> $GITHUB_OUTPUT
          echo "Captured AMI ID: $AMI_ID"

  update_asg:
    name: Update ASG with new AMI
    runs-on: ubuntu-latest
    needs: build_ami

    steps:
      - name: "Configure AWS Credentials for Demo"
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.DEMO_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEMO_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: "Configure AWS Credentials for Dev"
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get Launch Template ID and create new version
        run: |
          # Get Launch Template ID and store it
           LAUNCH_TEMPLATE_NAME=${{ secrets.LAUNCH_TEMPLATE_NAME }}
            AMI_ID=${{ needs.build_ami.outputs.ami_id }}

            # Fetch Launch Template ID
            LAUNCH_TEMPLATE_ID=$(aws ec2 describe-launch-templates \
              --filters "Name=launch-template-name,Values=${LAUNCH_TEMPLATE_NAME}" \
              --query "LaunchTemplates[0].LaunchTemplateId" --output text)

            if [ -z "$LAUNCH_TEMPLATE_ID" ]; then
              echo "Launch Template not found: ${LAUNCH_TEMPLATE_NAME}"
              exit 1
            fi


            # Create a new Launch Template Version
            NEW_VERSION=$(aws ec2 create-launch-template-version \
            --launch-template-id ${LAUNCH_TEMPLATE_ID} \
            --source-version '$Latest' \
            --launch-template-data "{\"ImageId\":\"${AMI_ID}\"}" \
            --query "LaunchTemplateVersion.VersionNumber" --output text)

            if [ -z "$NEW_VERSION" ]; then
              echo "Failed to create a new Launch Template Version."
              exit 1
            fi

            # Update Auto Scaling Group
            aws autoscaling update-auto-scaling-group \
              --auto-scaling-group-name ${{ secrets.ASG_NAME }} \
              --launch-template "LaunchTemplateId=${LAUNCH_TEMPLATE_ID},Version=$NEW_VERSION"

      - name: Start Instance Refresh
        run: |
          echo "Starting Instance Refresh for ASG: ${{ secrets.ASG_NAME }}"
          REFRESH_ID=$(aws autoscaling start-instance-refresh \
            --auto-scaling-group-name ${{ secrets.ASG_NAME }} \
            --strategy Rolling \
                --preferences '{"MinHealthyPercentage": 90, "InstanceWarmup": 300}' \
                --query "InstanceRefreshId" \
                --output text)

              if [ -z "$REFRESH_ID" ]; then
                echo "Failed to start instance refresh"
                exit 1
              fi

              echo "REFRESH_ID=${REFRESH_ID}" >> $GITHUB_ENV

      - name: Wait for Instance Refresh to Complete
        run: |
          while true; do
            echo "Checking status of Instance Refresh ID: $REFRESH_ID"
            STATUS=$(aws autoscaling describe-instance-refreshes \
              --auto-scaling-group-name ${{ secrets.ASG_NAME }} \
              --instance-refresh-ids ${{ env.REFRESH_ID }} \
              --query "InstanceRefreshes[0].Status" \
              --output text)

            echo "Current status: $STATUS"

            if [ "$STATUS" = "Successful" ]; then
              echo "Instance refresh completed successfully"
              exit 0
            elif [ "$STATUS" = "Failed" ] || [ "$STATUS" = "Cancelled" ]; then
              echo "Instance refresh $STATUS"
              exit 1
            else
              echo "Instance refresh status: $STATUS. Waiting..."
              sleep 60
            fi
          done
